import React, { useState } from 'react';
import { InterviewRoom, SurveyDemo } from './FCVFResearch';

const asset = (src: string) => `${import.meta.env.BASE_URL}${src}`;

export default function FCVFCase({setLightbox}) {
 const [active,setActive]=useState(3);
 const iterations=[
  {number:'01',title:'Original Excel',src:'project-media/fcvf-iterations/slide6-pic8.png',alt:'Original Excel Customer Value Framework assessment',tried:'The working assessment kept questions, formulas, and response values in one long workbook.',learned:'It preserved the framework, but added time, navigation friction, and exposed the score logic.',changed:'Move the workflow into a browser-based product.'},
  {number:'02',title:'Lean MVP',src:'project-media/fcvf-iterations/slide8-pic5.png',alt:'Early one-page HTML Customer Value Framework MVP',tried:'A usable one-page application built from basic HTML components with almost no visual styling.',learned:'Shipping early let product owners react before the team overbuilt the interface.',changed:'Use that feedback to design the single-page experience.'},
  {number:'03',title:'Designed one-page',src:'project-media/fcvf-iterations/slide9-pic5.png',alt:'Designed single-page Customer Value Framework application',tried:'A Figma-led interface with implemented score calculation and a clearer visual system.',learned:'Users still experienced cognitive load, and the live score created response-integrity risk.',changed:'Compare one-page and multi-page directions in interviews.'},
  {number:'04',title:'Multi-page flow',src:'project-media/fcvf-iterations/slide10-pic4.png',alt:'Multi-page Customer Value Framework application with pagination',tried:'A paginated assessment that focused attention on one portion of the framework at a time.',learned:'Interview feedback favored the clearer, lower-load experience.',changed:'Ship pagination and visible progress while keeping the score hidden.'}
 ];

 const current=iterations[active];
 const evidence=(src,alt,caption)=><figure className="fvEvidence"><button type="button" onClick={(e)=>{e.stopPropagation();setLightbox({src:asset(src),alt})}} aria-label={`Expand ${alt}`}><img src={asset(src)} alt={alt} loading="lazy"/><span aria-hidden="true">↗</span></button><figcaption>{caption}</figcaption></figure>;
 return <div className="fvEditorial">
  <section className="fvBrief">
   <div><h2>Better signals.<br/><em>Better decisions.</em></h2><p>Before Ford invested in a product idea, the Customer Value Framework helped teams test whether it created enough value for the customer—and decide whether to invest, improve, or stop.</p><p>The framework was useful. The workbook around it was the problem.</p></div>
   <div className="fvWorkbookBefore" aria-label="Recreation of the original Excel Customer Value Framework workbook">
    <header><span className="fvWorkbookIcon">X</span><div><strong>Customer Value Framework.xlsx</strong><small>Original assessment · score logic exposed</small></div><b>BEFORE</b></header>
    <div className="fvWorkbookChrome"><span>File</span><span>Home</span><span>Insert</span><span>Formulas</span><span>Data</span><i>fx&nbsp;&nbsp;=SUMPRODUCT(C12:C28,D12:D28)</i></div>
    <div className="fvWorkbookGrid" aria-hidden="true"><b></b>{['A','B','C','D','E'].map(x=><b key={x}>{x}</b>)}{['1','2','3','4','5','6'].map((row,r)=><React.Fragment key={row}><b>{row}</b><span className={r===0?'wide':''}>{r===0?'Customer evidence':''}</span><span>{r===1?'Demand':''}</span><span className="score">{[72,84,61,90,77,68][r]}</span><span>{r===2?'=C4*D4':''}</span><span></span></React.Fragment>)}</div>
    <footer><span>Long sheet</span><span>Editable formulas</span><span>Live score shapes answers</span></footer>
   </div>
  </section>
  <section className="fvRoleBridge" aria-label="How the engineering assignment expanded into product ownership"><header><span></span><strong>The assignment started with implementation. I carried it through research and into the shipped direction.</strong></header><div className="fvRoleTrack"><article><b>01</b><strong>Turn the Excel assessment into a stable web application.</strong></article><i aria-hidden="true">→</i><article><b>02</b><strong>Lead four interviews and compare two interaction models.</strong></article><i aria-hidden="true">→</i><article className="isDecision"><b>03</b><strong>Move to pagination and hide the score until completion.</strong></article></div><footer><strong>Research directly changed how the product worked.</strong></footer></section>
  <section className="fvResearch"><header><h2>Four interviews changed<br/>the product's direction.</h2><InterviewRoom/></header><div className="fvResearchNotes"><p>I led four user interviews to compare one-page and multi-page directions. Two findings shaped the product:</p><article><span>Finding 01</span><svg className="fvTestSketch" viewBox="0 0 190 74" aria-hidden="true"><rect x="1" y="1" width="188" height="70" rx="9" fill="none" stroke="currentColor"/><path d="M64 1V71M126 1V71" stroke="currentColor"/><path d="M11 17H52M11 28H52M11 39H41M137 17H177M137 28H177M137 39H166" stroke="currentColor" opacity=".25"/><rect x="72" y="10" width="46" height="52" rx="4" fill="#163f5b"/><path d="M81 23H109M81 32H109M81 41H100" stroke="#e2e8e7"/></svg><h3>Less on the screen.<br/>More focus on the answer.</h3><p>The full assessment felt overwhelming. Pagination gave users one portion of the framework to work through at a time.</p></article><article><span>Finding 02</span><svg className="fvTestSketch" viewBox="0 0 190 74" aria-hidden="true"><rect x="1" y="1" width="188" height="70" rx="9" fill="none" stroke="currentColor"/><path d="M18 22H103M18 36H103M18 50H103" stroke="currentColor" opacity=".25"/><rect x="118" y="12" width="58" height="47" rx="4" fill="#163f5b"/><path d="M138 33V27a9 9 0 0 1 18 0V33" fill="none" stroke="#dce5e6" strokeWidth="2"/><rect x="135" y="32" width="24" height="18" rx="2" fill="#dce5e6"/><path d="M147 38V44" stroke="#163f5b" strokeWidth="2"/></svg><h3>A visibly changing score was originally on the screen as the user went through the form.</h3><p>Showing the score during the assessment could encourage people to adjust answers toward a result and unlocked the next step for engineering.</p></article></div></section>
  <SurveyDemo/>
  <section className="fvWorkbench"><header><div><h2>Four builds.<br/>One clearer experience.</h2></div><p>Each version answered the next uncertainty. Explore the original artifacts and the decision behind each iteration.</p></header><div className="fvBuildNav" role="group" aria-label="Choose a prototype version">{iterations.map((item,i)=><button key={item.number} type="button" aria-pressed={active===i} onClick={()=>setActive(i)}><span>{item.number}</span>{item.title}</button>)}</div><div className="fvBuild" aria-live="polite"><div className="fvBuildImage">{evidence(current.src,current.alt,`Original project artifact / Build ${current.number}`)}</div><div className="fvBuildNotes"><h3>{current.title}</h3><dl><dt>Built</dt><dd>{current.tried}</dd><dt>Learned</dt><dd>{current.learned}</dd><dt>Decision</dt><dd>{current.changed}</dd></dl></div></div></section>
  <section className="fvLogic"><div><h2>Keep the engine.<br/><em>Rethink the controls.</em></h2><p>The workbook’s response values and formulas were the scoring foundation. Moving to the web meant preserving that logic while protecting it from accidental edits and score gaming.</p></div><div className="fvFormulaPair">{evidence('project-media/fcvf-iterations/slide6-pic5.png','Original Excel response values','01 / Response values')}{evidence('project-media/fcvf-iterations/slide6-pic6.png','Original Excel scoring formula','02 / Scoring logic')}</div></section>
  <section className="fvDelivery"><header><h2>A clearer path from<br/>feedback to customer value.</h2></header>{evidence('project-media/ford-after.webp','Final Ford Customer Value Framework web experience','Shipped web experience / Multi-page flow · Visible progress · Score after completion')}<div className="fvHandoff"><div className="fvOutcome"><small>FCVF / PROJECT OUTCOME</small><strong>+25%</strong><span>feedback volume</span></div><div><h3>Research carried through to the build.</h3><p>I interviewed users, evaluated the interface directions, implemented frontend work, and tested with the team. The shipped experience made the assessment easier to work through while strengthening response integrity.</p></div></div></section>
 </div>
}
