import React, { useState } from 'react';
import { InterviewRoom, SurveyDemo } from './FCVFResearch';

const asset = (src: string) => `${import.meta.env.BASE_URL}${src}`;

export default function FCVFCase({setLightbox}) {
 const [active,setActive]=useState(3);
 const iterations=[
  {number:'01',title:'Original Excel',src:'project-media/fcvf-iterations/slide6-pic8.png',alt:'Original Excel Customer Value Framework assessment',tried:'The working assessment kept questions, formulas, and response values in one long workbook.',learned:'It preserved the framework, but added time, navigation friction, and exposed the score logic.',changed:'Move the workflow into a browser-based product.'},
  {number:'02',title:'Lean MVP',src:'project-media/fcvf-iterations/slide8-pic5.png',alt:'Early one-page HTML Customer Value Framework MVP',tried:'A usable one-page application built from basic HTML components with almost no visual styling.',learned:'Shipping early let product owners react before the team overbuilt the interface.',changed:'Use that feedback to design the single-page experience.'},
  {number:'03',title:'Designed one-page',src:'project-media/fcvf-iterations/slide9-pic5.png',alt:'Designed single-page Customer Value Framework application',tried:'A Figma-led interface with implemented score calculation and a clearer visual system.',learned:'Users still experienced cognitive load, and the live score created response-integrity risk.',changed:'Compare one-page and multi-page directions in interviews.'},
  {number:'04',title:'Multi-page flow',src:'project-media/fcvf-iterations/slide10-pic4.png',alt:'Multi-page Customer Value Framework application with pagination',tried:'A paginated assessment that focused attention on one portion of the framework at a time.',learned:'Interview feedback favored the clearer, lower-load experience.',changed:'Ship pagination and visible progress while keeping the score hidden.'}
 ];

 const current=iterations[active];
 const evidence=(src,alt,caption)=><figure className="fvEvidence"><button type="button" onClick={(e)=>{e.stopPropagation();setLightbox({src:asset(src),alt})}} aria-label={`Expand ${alt}`}><img src={asset(src)} alt={alt} loading="lazy"/><span aria-hidden="true">↗</span></button><figcaption>{caption}</figcaption></figure>;
 return <div className="fvEditorial">
  <section className="fvBrief">
   <div><span className="fvEyebrow">01 / The brief</span><h2>Better signals.<br/><em>Better decisions.</em></h2><p>Before Ford teams invested in a product idea, the Customer Value Framework helped them ask a more fundamental question: does this create enough value for the customer?</p><p>The assessment worked. Its Excel container made it slow to navigate, easy to disrupt, and too revealing about how answers were scored.</p></div>
   <div className="fvBlueprint" aria-label="Customer value decision process"><header><span>FORD / PRODUCT ENGINEERING</span><span>FIG. 01</span></header><div className="fvDrawing"><svg viewBox="0 0 460 220" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="1"><path d="M45 105H415M230 20V200" strokeDasharray="4 6" opacity=".5"/><circle cx="230" cy="105" r="76"/><circle cx="230" cy="105" r="66"/><path d="M154 105L193 66H267L306 105L267 144H193Z"/><path d="M193 66L230 105L267 66M193 144L230 105L267 144"/><path d="M65 58V155M60 58H70M60 155H70M83 58H142M83 155H142"/><path d="M320 52L348 24H424M320 160L348 188H424"/><circle cx="230" cy="105" r="12"/></g><text x="359" y="18" fill="currentColor" fontSize="9" letterSpacing="1">EVIDENCE IN</text><text x="351" y="204" fill="currentColor" fontSize="9" letterSpacing="1">DECISION OUT</text></svg></div><h3>Is the value real?</h3><ol><li><b>01</b> Product idea</li><li><b>02</b> Customer evidence</li><li><b>03</b> Invest, improve, or stop</li></ol><footer><span>DESIGN INTENT</span><strong>Make judgment repeatable.</strong></footer></div>
  </section>
  <section className="fvResearch"><header><span className="fvEyebrow">02 / Research & calibration</span><h2>Four interviews.<br/>A different direction.</h2><InterviewRoom/></header><div className="fvResearchNotes"><p>I led four user interviews to compare one-page and multi-page directions. Two findings shaped the product:</p><article><span>Finding 01 / Cognitive load</span><svg className="fvTestSketch" viewBox="0 0 190 74" aria-hidden="true"><rect x="1" y="1" width="188" height="70" rx="9" fill="none" stroke="currentColor"/><path d="M64 1V71M126 1V71" stroke="currentColor"/><path d="M11 17H52M11 28H52M11 39H41M137 17H177M137 28H177M137 39H166" stroke="currentColor" opacity=".25"/><rect x="72" y="10" width="46" height="52" rx="4" fill="#163f5b"/><path d="M81 23H109M81 32H109M81 41H100" stroke="#e2e8e7"/></svg><h3>Less on the screen.<br/>More focus on the answer.</h3><p>The full assessment felt overwhelming. Pagination gave users one portion of the framework to work through at a time.</p></article><article><span>Finding 02 / Response integrity</span><svg className="fvTestSketch" viewBox="0 0 190 74" aria-hidden="true"><rect x="1" y="1" width="188" height="70" rx="9" fill="none" stroke="currentColor"/><path d="M18 22H103M18 36H103M18 50H103" stroke="currentColor" opacity=".25"/><rect x="118" y="12" width="58" height="47" rx="4" fill="#163f5b"/><path d="M138 33V27a9 9 0 0 1 18 0V33" fill="none" stroke="#dce5e6" strokeWidth="2"/><rect x="135" y="32" width="24" height="18" rx="2" fill="#dce5e6"/><path d="M147 38V44" stroke="#163f5b" strokeWidth="2"/></svg><h3>A visible score becomes a target.</h3><p>Showing the score during the assessment could encourage people to adjust answers toward a result. Progress was the useful signal to show.</p></article></div></section>
  <SurveyDemo/>
  <section className="fvWorkbench"><header><div><span className="fvEyebrow">03 / The prototype workbench</span><h2>Four builds.<br/>One clearer experience.</h2></div><p>Each version answered the next uncertainty. Explore the original artifacts and the decision behind each iteration.</p></header><div className="fvBuildNav" role="group" aria-label="Choose a prototype version">{iterations.map((item,i)=><button key={item.number} type="button" aria-pressed={active===i} onClick={()=>setActive(i)}><span>{item.number}</span>{item.title}</button>)}</div><div className="fvBuild" aria-live="polite"><div className="fvBuildImage">{evidence(current.src,current.alt,`Original project artifact / Build ${current.number}`)}</div><div className="fvBuildNotes"><span className="fvEyebrow">BUILD {current.number} / 04</span><h3>{current.title}</h3><dl><dt>Built</dt><dd>{current.tried}</dd><dt>Learned</dt><dd>{current.learned}</dd><dt>Decision</dt><dd>{current.changed}</dd></dl></div></div></section>
  <section className="fvLogic"><div><span className="fvEyebrow">04 / Under the hood</span><h2>Keep the engine.<br/><em>Rethink the controls.</em></h2><p>The workbook’s response values and formulas were the scoring foundation. Moving to the web meant preserving that logic while protecting it from accidental edits and score gaming.</p></div><div className="fvFormulaPair">{evidence('project-media/fcvf-iterations/slide6-pic5.png','Original Excel response values','01 / Response values')}{evidence('project-media/fcvf-iterations/slide6-pic6.png','Original Excel scoring formula','02 / Scoring logic')}</div></section>
  <section className="fvDelivery"><header><span className="fvEyebrow">05 / On the road</span><h2>A clearer path from<br/>feedback to customer value.</h2></header>{evidence('project-media/ford-after.webp','Final Ford Customer Value Framework web experience','Shipped web experience / Multi-page flow · Visible progress · Score after completion')}<div className="fvHandoff"><div className="fvOutcome"><small>FCVF / PROJECT OUTCOME</small><strong>+25%</strong><span>feedback volume</span></div><div><h3>Research carried through to the build.</h3><p>I interviewed users, evaluated the interface directions, implemented frontend work, and tested with the team. The shipped experience made the assessment easier to work through while strengthening response integrity.</p></div></div></section>
 </div>
}
