import React, { useState } from 'react';
import './finsimple.css';
const asset=(src:string)=>`${import.meta.env.BASE_URL}${src}`;
const builds=[
 {title:'Make the behavior tangible',stage:'01 / Prototype',src:'project-media/finsimple-dummy.png',alt:'FinSimple prototype with synthetic data',copy:'Synthetic data made the Previous Estimates interaction testable before integration.'},
 {title:'Make it native to the platform',stage:'02 / AEM component',src:'project-media/finsimple-aem.png',alt:'FinSimple AEM component implementation',copy:'The experience became a reusable AEM component inside the existing product.'},
 {title:'Carry it into the live journey',stage:'03 / Customer release',src:'project-media/finsimple-live.png',alt:'Released FinSimple Previous Estimates experience',copy:'Integration, testing, and release coordination carried the feature into the customer-facing flow.'}
];
const layers=[
 {name:'Web experience',label:'Customer intent',detail:'Find a previous estimate and continue from the existing journey.',fields:['Customer context','Selected estimate']},
 {name:'AEM component',label:'Platform fit',detail:'Present the feature through reusable components in the established platform.',fields:['Shared components','Interface behavior']},
 {name:'API layer',label:'The handoff',detail:'Carry customer and estimate context across the integration boundary.',fields:['Customer context','Estimate context']},
 {name:'Salesforce',label:'System of record',detail:'Connect the customer-facing workflow to the downstream record.',fields:['Durable record','Workflow continuity']}
];
export default function FinSimpleCase({setLightbox}){
 const [layer,setLayer]=useState(0);
 const [build,setBuild]=useState(2);
 const current=builds[build];
 const evidence=(src,alt,caption)=><figure className="fseEvidence"><button type="button" onClick={e=>{e.stopPropagation();setLightbox({src:asset(src),alt})}} aria-label={`Expand ${alt}`}><img src={asset(src)} alt={alt} loading="lazy"/><span>View original ↗</span></button><figcaption>{caption}</figcaption></figure>;
 return <div className="fseEditorial">
 <section className="fseReturn fseReturnLiteral"><div><span className="fseIndex">01 / Previous Estimates</span><h2>Find an earlier estimate.<br/><em>Continue from there.</em></h2><p>Customers had already spent time creating vehicle estimates. Previous Estimates gave them a place to revisit that work within the existing FinSimple experience.</p><ol className="fseCustomerSteps"><li><b>01</b><div><strong>Open Previous Estimates</strong><span>Return to the estimates already created.</span></div></li><li><b>02</b><div><strong>Choose an estimate</strong><span>Find the earlier vehicle estimate to revisit.</span></div></li><li><b>03</b><div><strong>Continue the existing journey</strong><span>Pick up the workflow from that estimate.</span></div></li></ol></div><div className="fseRealScreen">{evidence('project-media/finsimple-live.png','Released FinSimple Previous Estimates interface','The actual released interface · select to view full size')}</div></section>
 <section className="fsePlatform"><header><div><span className="fseIndex">02 / Connected below the surface</span><h2>One simple action.<br/><em>Four connected layers.</em></h2></div><p>FinSimple already had customers, shared components, and production systems. The new feature had to feel native while fitting the AEM, API, Salesforce, QA, and release work behind it.</p></header><div className="fseConnection"><div className="fseLayerStack" role="group" aria-label="Explore the platform layers">{layers.map((item,i)=><button type="button" key={item.name} aria-pressed={layer===i} onClick={()=>setLayer(i)}><span>0{i+1}</span><strong>{item.name}</strong><i aria-hidden="true">{layer===i?'●':'○'}</i></button>)}</div><div className="fseConnector" aria-hidden="true"><span/><span/><span/></div><div className="fseContextRecord" aria-live="polite"><header><span>CONTEXT IN MOTION</span><b>0{layer+1} / 04</b></header><span className="fseIndex">{layers[layer].label}</span><h3>{layers[layer].name}</h3><p>{layers[layer].detail}</p><dl>{layers[layer].fields.map((field,i)=><div key={field}><dt>0{i+1}</dt><dd>{field}</dd><span>✓</span></div>)}</dl><footer>The customer’s earlier work travels forward.</footer></div></div></section>
 <section className="fseBuild"><header><div><span className="fseIndex">03 / From prototype to production</span><h2>Built into the real thing.</h2></div><p>Explore the original project artifacts from synthetic data to the released feature.</p></header><div className="fseBuildTabs" role="group" aria-label="Select a FinSimple build stage">{builds.map((item,i)=><button type="button" key={item.stage} onClick={()=>setBuild(i)} aria-pressed={build===i}>{item.stage}</button>)}</div><div className="fseBuildStage"><div>{evidence(current.src,current.alt,'Original project artifact · expand for full detail')}</div><aside aria-live="polite"><span className="fseIndex">{current.stage}</span><h3>{current.title}</h3><p>{current.copy}</p><div className="fseSpecLines" aria-hidden="true"><i/><i/><i/><i/></div><span className="fseIndex">My ownership</span><p>Requirements, AEM component work, API integration, testing, and cross-team release coordination.</p></aside></div></section>
 <section className="fseDelivery"><div><span className="fseIndex">04 / Coordinating the release</span><h2>The handoffs were<br/><em>part of the product.</em></h2><p>I coordinated across five teams and 50 people to move the feature through the existing platform and release process.</p><p>That work connected customer-facing behavior to the systems and people responsible for getting it into production.</p></div><div className="fseReleasePass"><header><span>FIN SIMPLE / DELIVERY RECORD</span><b>RELEASED</b></header><div className="fsePassNumber">05<span>cross-functional teams</span></div><ol>{['Requirements','AEM component','API integration','QA & validation','Production release'].map((item,i)=><li key={item}><span>0{i+1}</span><strong>{item}</strong><b>✓</b></li>)}</ol><footer><strong>10%</strong><span>ahead of schedule</span></footer></div></section>
 <section className="fseOutcome"><svg viewBox="0 0 260 190" aria-hidden="true"><path d="M15 158H72Q102 158 102 126V69Q102 38 132 38H243" stroke="#65a6db" strokeWidth="2" fill="none"/><path d="M15 168H82Q112 168 112 135V79Q112 48 142 48H243" stroke="#65a6db" strokeDasharray="4 7" fill="none"/><circle cx="42" cy="158" r="12" fill="#0b2947" stroke="#c9e7fb" strokeWidth="2"/><path d="M36 158L41 163L49 153M232 29L242 38L232 47" fill="none" stroke="#d4edff" strokeWidth="2"/></svg><div><span className="fseIndex">The shipped experience</span><h2>Pick up the estimate.<br/>Keep moving forward.</h2><p>Previous Estimates gave customers a continuation point within the existing product, preserving the platform workflow while making earlier work easier to revisit and act on.</p></div></section>
 </div>
}
