import React, { useEffect, useRef, useState } from 'react';
import './kohler-demo.css';

type Page = 'search' | 'work' | 'activity' | 'audit';
type Shipment = { id: string; name: string; sku: string; description: string; destination: string; language: string; dock: string; items: number; age: number; priority: string; status: string; team: string; associate: string; date: string; checks: boolean[]; exception: string; review: string };
type AuditEvent = { id: string; shipment: string; timestamp: string; activity: string; user: string; previous: string; next: string; location: string; details: string };
const products = [
 ['Kitchen Faucet','K-596-VS','Faucet assembly · Vibrant Stainless'], ['Toilet – Wellworth','K-3998','Complete toilet set'],
 ['Vanity – Caxton 60"','K-3051','Vanity cabinet · White'], ['Shower Door – Revel','K-7075','Frameless 60" shower door'],
 ['Sink – Vault','K-3821','Kitchen sink · Stainless Steel'], ['Bath Accessory Set','K-14435','Towel bar, ring, paper holder'],
 ['Lighting – Verdera Sconce','K-26024','2-Light LED vanity light'], ['Medicine Cabinet','K-CB-CLR','24" mirrored cabinet'],
 ['Toilet Seat','K-4636','Quiet-Close seat · White'], ['Shower Trim','K-T14420-4','Rite-Temp trim kit'],
 ['Bathtub – Archer','K-1122','60" alcove bathtub · White'], ['Purist Single-Handle Faucet','K-14406','Widespread bathroom faucet'],
 ['Mirror – Essential 30"','K-26050','Framed mirror · Brushed Nickel'], ['Towel Warmer','K-99693','Wall-mounted towel warmer'],
];
const destinations = [['Dubai, UAE','Arabic, English'],['Bengaluru, India','Hindi, English'],['Shanghai, China','Chinese, English']];
const statuses = [...Array(36).fill('Completed'), ...Array(20).fill('In Progress'), ...Array(9).fill('Pending'), ...Array(4).fill('Halted'), ...Array(20).fill('Needs Review'), ...Array(9).fill('Assigned')];
function seedShipments(): Shipment[] {
 return Array.from({length:98}, (_,i) => {
  const p=products[i%14], market=destinations[i===11?0:i%3], status=statuses[((i===11?12:i===12?11:i)*37)%98];
  return {id:`SHP-${10482+i}`,name:p[0],sku:p[1],description:p[2],destination:market[0],language:market[1],dock:`Dock ${['A3','B1','C2','A1','B3','C1','A2','B2','C3','A4'][i%10]}`,items:[12,8,6,4,20,36,10,8,24,16,2,14,6,4][i%14],age:[5,4,2,7,1,6,3,9,1,5,8,3,2,10][i%14],priority:i%7===0?'Urgent':i%3===0?'High':'Normal',status,team:`Team ${['A','B','C'][i%3]}`,associate:['T. Zimmerman','A. Patel','J. Lee','M. Rivera'][i%4],date:`2026-04-${String(24+i%7).padStart(2,'0')}`,checks:status==='Completed'?Array(5).fill(true):Array(5).fill(false),exception:['Needs Review','Halted'].includes(status)?'Destination label is unavailable. Supervisor review is required.':'',review:status==='Completed'?'Approved':'Generated'};
 });
}
function seedAudit(shipments:Shipment[]): AuditEvent[] {
 const actions=['Created','Assigned to picker','Barcode scanned','Status updated','Moved to staging','Pending review','Status updated','Picked','Moved to staging','Loaded for dispatch','Status updated','Barcode scanned','Status updated','Backlog resolved'];
 const previous=['—','Backlogged','Assigned','Ready to Pick','Picked','Staged','Pending Review','Ready to Pick','Picked','Staged','Backlogged','Ready to Pick','Picked','Backlogged'];
 const next=['Backlogged','Assigned','Ready to Pick','Picked','Staged','Pending Review','Ready to Pick','Picked','Staged','Loaded','Ready to Pick','Picked','Staged','Loaded'];
 const details=['Shipment created','Assigned to Picker 12','All items scanned','Items picked (8)','Moved to staging','Quality check required','QA complete','Items picked (36)','Moved to staging','Loaded on truck #7721','Inventory available','All items scanned','Moved to staging','Cleared from backlog'];
 return Array.from({length:186},(_,i)=>{const s=shipments[i%98],n=i%14;return {id:`seed-${i}`,shipment:s.id,timestamp:`2026-04-${String(24+Math.floor(i/5)%7).padStart(2,'0')}T${String(8+i%10).padStart(2,'0')}:${String((12+i*11)%60).padStart(2,'0')}:00`,activity:actions[n],user:s.associate,previous:previous[n],next:next[n],location:n===4||n===8?'Staging C2':s.dock,details:details[n]}});
}
const navigation: [Page,string,string][] = [['search','Shipment Search','home'],['work','Work Instructions','document'],['activity','Activity Overview','activity'],['audit','Audit History','audit']];
function Icon({name}:{name:string}) {
 const paths: Record<string,React.ReactNode>={home:<><path d="m3 10 9-7 9 7v10H3z"/><path d="M9 20v-7h6v7"/></>,document:<><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/></>,activity:<path d="M2 12h5l3-8 4 16 3-8h5"/>,audit:<><rect x="6" y="5" width="14" height="16" rx="2"/><path d="M4 17V3h13M9 10h8M9 14h8M9 18h5"/></>,box:<><path d="m3 7 9-4 9 4v10l-9 4-9-4zM3 7l9 5 9-5M12 12v9M7 5l10 5"/></>,pin:<><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 0 1 14 0z"/><circle cx="12" cy="10" r="2"/></>,globe:<><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c5 5 5 13 0 18-5-5-5-13 0-18"/></>,clock:<><circle cx="12" cy="13" r="8"/><path d="M12 8v5l3 2M9 2h6"/></>,check:<><rect x="3" y="3" width="18" height="18" rx="2"/><path d="m7 12 3 3 7-7"/></>,barcode:<path d="M3 4v16M6 4v16M10 4v16M12 4v16M16 4v16M20 4v16"/>,search:<><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></>};
 return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]||paths.document}</svg>;
}
function Pill({value}:{value:string}) { return <span className={`kd-pill kd-${value.toLowerCase().replace(/ /g,'-')}`}>{value}</span> }
const documentNames=['Translated Installation Guide','Warranty Labels','Certification Labels'];
const tasks=['Translated installation guide','Destination warranty labels','Destination certification labels','Review shipment manifest','Pack all items and prepare for shipping'];
const formatTime=(value:string)=>new Date(value).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'2-digit',minute:'2-digit'});

export default function KohlerDemo() {
 const [shipments,setShipments]=useState(seedShipments);
 const [events,setEvents]=useState(()=>seedAudit(seedShipments()));
 const [page,setPage]=useState<Page>('search');
 const [selected,setSelected]=useState('SHP-10493');
 const [role,setRole]=useState('Supervisor');
 const [query,setQuery]=useState(''),[status,setStatus]=useState(''),[date,setDate]=useState(''),[destination,setDestination]=useState(''),[associate,setAssociate]=useState('');
 const [more,setMore]=useState(false),[scan,setScan]=useState(''),[notice,setNotice]=useState('');
 const [pagination,setPagination]=useState(1),[sort,setSort]=useState(''),[ascending,setAscending]=useState(true);
 const [dialog,setDialog]=useState<{type:'document'|'exception'|'event'; index?:number; event?:AuditEvent; shipment?:string}|null>(null);
 const [reason,setReason]=useState('');
 const [guided,setGuided]=useState(true),[scenario,setScenario]=useState<'normal'|'exception'>('normal');
 const [scanning,setScanning]=useState(false),[viewed,setViewed]=useState(false),[resolved,setResolved]=useState(false);
 const scanTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const dialogRef=useRef<HTMLDivElement>(null);
 const shipment=shipments.find(s=>s.id===selected)!;
 const supervisor=role==='Supervisor';
 useEffect(()=>{
  if(!dialog)return;
  const previous=document.activeElement as HTMLElement|null;
  dialogRef.current?.querySelector<HTMLButtonElement>('button')?.focus({preventScroll:true});
  dialogRef.current?.scrollIntoView({block:'nearest',behavior:'instant' as ScrollBehavior});
  return()=>previous?.focus({preventScroll:true});
 },[dialog]);
 function dialogKeys(e:React.KeyboardEvent<HTMLDivElement>) {
  if(e.key==='Escape'){e.preventDefault();setDialog(null);return}
  if(e.key!=='Tab')return;
  const controls=Array.from(dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), textarea:not(:disabled), select:not(:disabled), [tabindex="0"]')||[]);
  const first=controls[0],last=controls[controls.length-1];
  if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}
  else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}
 }
 useEffect(()=>()=>{if(scanTimer.current)clearTimeout(scanTimer.current)},[]);
 useEffect(()=>{if(page!=='search'){if(scanTimer.current)clearTimeout(scanTimer.current);setScanning(false)}},[page]);
 function navigate(next:Page) {setPage(next);setQuery('');setStatus('');setDate('');setDestination('');setAssociate('');setPagination(1);setSort('');setNotice('')}
 function openShipment(id:string) {setSelected(id);setViewed(false);navigate('work')}
 function lookup(value:string) {
  const found=shipments.find(s=>s.id.toLowerCase()===value.trim().toLowerCase()||s.sku.toLowerCase()===value.trim().toLowerCase());
  if(found){record(found,'Barcode scanned',found.status,`Simulated barcode lookup: ${value.trim()}. Product and destination retrieved from the sample record.`);openShipment(found.id);setScan('')}
  else setNotice('No shipment found. Try SHP-10493 or SKU K-14406.');
 }
 function scanSample() {
  if(scanning)return;setScanning(true);setScan('SHP-10493');setNotice('Scanning sample barcode…');
  scanTimer.current=setTimeout(()=>{setScanning(false);lookup('SHP-10493');setNotice('Barcode matched SHP-10493. Product, destination, and sample packet loaded.');scanTimer.current=null},1000);
 }
 function record(s:Shipment,activity:string,next:string,details:string) {
  setEvents(old=>[{id:`event-${Date.now()}-${old.length}`,shipment:s.id,timestamp:new Date().toISOString(),activity,user:supervisor?'T. Zimmerman':'J. Lee',previous:s.status,next,location:s.dock,details},...old]);
 }
 function updateShipment(change:Partial<Shipment>,activity:string,details:string) {
  const next={...shipment,...change};setShipments(old=>old.map(s=>s.id===shipment.id?next:s));record(shipment,activity,next.status,details);
 }
 function toggleTask(index:number) {
  if(shipment.exception||shipment.status==='Rejected'||shipment.status==='Completed')return;
  const checks=shipment.checks.map((value,i)=>i===index?!value:value);
  // Removing an earlier verification also invalidates the dependent packing steps.
  if(index<3&&!checks[index]){checks[3]=false;checks[4]=false}if(index===3&&!checks[3])checks[4]=false;
  updateShipment({checks,status:'In Progress'},'Step verified',`${tasks[index]}: ${checks[index]?'verified':'verification removed'}`);
 }
 function complete() {
  if(!shipment.checks.every(Boolean)||shipment.exception||['Rejected','Needs Review','Halted'].includes(shipment.status))return;
  updateShipment({status:'Completed',review:'Approved'},'Shipment completed',`All 5 preparation checks verified. Sample document packet attached for ${shipment.destination}.`);setNotice(`${shipment.id} completed. Its completion record is available in Audit History.`);
 }
 function review(approved:boolean) {
  if(!supervisor||!shipment.exception||!reason.trim())return;
  updateShipment({status:approved?'In Progress':'Rejected',exception:approved?'':shipment.exception,review:approved?'Approved':'Rejected'},approved?'Review approved':'Review rejected',reason.trim());setReason('');setNotice(approved?'Exception resolved by supervisor. Continue the preparation checklist.':'Shipment rejected. Reopen it for corrections before preparing it again.');
  if(approved)setResolved(true);
 }
 function reset() {if(scanTimer.current)clearTimeout(scanTimer.current);setScanning(false);const fresh=seedShipments();setShipments(fresh);setEvents(seedAudit(fresh));setSelected('SHP-10493');setRole('Supervisor');navigate('search');setScan('');setMore(false);setReason('');setDialog(null);setViewed(false);setResolved(false);setNotice('Sample data reset.')}
 function startScenario(next:'normal'|'exception') {reset();setScenario(next);setGuided(true);setRole('Associate');setNotice('')}
 function matches(s:Shipment) {return (!date||s.date===date)&&(!destination||s.destination===destination)&&(!associate||s.associate===associate)}
 const filteredShipments=shipments.filter(s=>matches(s)&&(!status||s.status===status)&&`${s.id} ${s.name} ${s.sku} ${s.description} ${s.destination}`.toLowerCase().includes(query.toLowerCase()));
 const activityShipments=[...filteredShipments].sort((a,b)=>{
  const latest=(s:Shipment)=>events.find(e=>e.shipment===s.id)?.timestamp||`${s.date}T08:00:00`;
  return latest(b).localeCompare(latest(a));
 });
 const filteredEvents=events.filter(e=>{const s=shipments.find(x=>x.id===e.shipment)!;return (!date||e.timestamp.slice(0,10)===date)&&(!destination||s.destination===destination)&&(!associate||e.user===associate)&&(!status||e.next===status)&&`${e.shipment} ${e.activity} ${e.user} ${e.details} ${s.name}`.toLowerCase().includes(query.toLowerCase())});
 const total=page==='audit'?filteredEvents.length:filteredShipments.length;
 const pages=Math.max(1,Math.ceil(total/14)),current=Math.min(pagination,pages);
 const orderedShipments=[...filteredShipments].sort((a,b)=>sort?String(a[sort as keyof Shipment]).localeCompare(String(b[sort as keyof Shipment]),undefined,{numeric:true})*(ascending?1:-1):0);
 const orderedEvents=[...filteredEvents].sort((a,b)=>sort?String(a[sort as keyof AuditEvent]).localeCompare(String(b[sort as keyof AuditEvent]),undefined,{numeric:true})*(ascending?1:-1):0);
 const visibleShipments=orderedShipments.slice((current-1)*14,current*14),visibleEvents=orderedEvents.slice((current-1)*14,current*14);
 const counts=(value:string)=>shipments.filter(s=>s.status===value).length;
 const completed=counts('Completed'),progress=counts('In Progress'),pending=counts('Pending'),halted=counts('Halted'),inReview=counts('Needs Review')+counts('Rejected'),other=counts('Assigned');
 const distribution=[['Completed',completed,'#323232'],['In Progress',progress,'#93b8dc'],['Pending',pending,'#eed490'],['Halted',halted,'#c58978'],['In Review',inReview,'#b5a4cf'],['Other',other,'#dededc']] as const;
 let cursor=0;const donut=distribution.map(([,count,color])=>{const start=cursor;cursor+=count/98*100;return `${color} ${start}% ${cursor}%`}).join(',');
 function sortBy(key:string){setAscending(sort===key?!ascending:true);setSort(key)}
 function sortHeading(label:string,key:string){return <button type="button" className="kd-sort" onClick={()=>sortBy(key)}>{label} <span>{sort===key?(ascending?'↑':'↓'):'↕'}</span></button>}
 function filters(audit=false) {return <><div className="kd-filters"><input aria-label={audit?'Search audit history':'Search shipments'} placeholder="Search by name, shipment ID, or description…" value={query} onChange={e=>{setQuery(e.target.value);setPagination(1)}}/><select aria-label="Status" value={status} onChange={e=>{setStatus(e.target.value);setPagination(1)}}><option value="">Status · All</option>{[...new Set(audit?events.map(e=>e.next):shipments.map(s=>s.status))].sort().map(s=><option key={s}>{s}</option>)}</select><input type="date" aria-label="Date" value={date} onChange={e=>{setDate(e.target.value);setPagination(1)}}/><button type="button" aria-expanded={more} onClick={()=>setMore(!more)}>More Filters…</button></div>{more&&<div className="kd-extra-filters"><label>Destination<select value={destination} onChange={e=>{setDestination(e.target.value);setPagination(1)}}><option value="">All destinations</option>{destinations.map(([d])=><option key={d}>{d}</option>)}</select></label><label>Associate<select value={associate} onChange={e=>{setAssociate(e.target.value);setPagination(1)}}><option value="">All associates</option>{['T. Zimmerman','A. Patel','J. Lee','M. Rivera'].map(a=><option key={a}>{a}</option>)}</select></label></div>}{(query||status||date||destination||associate)&&<button className="kd-clear" type="button" onClick={()=>{setQuery('');setStatus('');setDate('');setDestination('');setAssociate('');setPagination(1)}}>Clear filters</button>}</>}
 function pager(audit=false){return <div className="kd-pagination"><span>{total?`Showing ${(current-1)*14+1}–${Math.min(current*14,total)} of ${total}`:'No matching'} {audit?'audit events':'shipments'}</span><div><button type="button" aria-label="Previous page" disabled={current===1} onClick={()=>setPagination(current-1)}>‹</button>{Array.from({length:pages},(_,i)=>i+1).filter(n=>n===1||n===pages||Math.abs(n-current)<=1).map((n,i,all)=><React.Fragment key={n}>{i>0&&n-all[i-1]>1&&<span>…</span>}<button type="button" aria-label={`Page ${n}`} aria-current={n===current?'page':undefined} onClick={()=>setPagination(n)}>{n}</button></React.Fragment>)}<button type="button" aria-label="Next page" disabled={current===pages} onClick={()=>setPagination(current+1)}>›</button></div></div>}
 function preview(index:number,s=shipment){setViewed(true);setDialog({type:'document',index,shipment:s.id})}
 function downloadSample(index:number,s:Shipment) {
  const text=`SHIP ANYWHERE — SAMPLE DOCUMENT\n${documentNames[index]}\nShipment: ${s.id}\nProduct: ${s.name}\nSKU: ${s.sku}\nDestination: ${s.destination}\nLanguage pack: ${s.language}\nFormat: A4\n\nPortfolio demonstration only. This is a sample packet, not an approved translation, warranty, certification, or export document.\n\nPreparation task: ${tasks[index]}\nSource: predefined demo shipment record.\nReview status: ${s.review}\n`;
  const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`${s.id}-${['installation-guide','warranty-labels','certification-labels'][index]}-sample.txt`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }
 const dialogShipment=shipments.find(s=>s.id===(dialog?.shipment||dialog?.event?.shipment))||shipment;
 const guideStep=page==='search'?0:shipment.status==='Completed'?4:shipment.exception?2:!viewed?1:scenario==='exception'&&!resolved?2:shipment.checks.every(Boolean)?3:2;
 const guideTitle=page==='audit'?'Every action stays attached to the shipment.':page==='activity'?'See the shipment in the warehouse overview.':page==='search'?'Start with the barcode on the shipment.':shipment.status==='Completed'?'The shipment is ready. Follow its audit trail.':shipment.exception?(supervisor?'Resolve the issue before work continues.':'The shipment stops here. A supervisor needs to review it.'):!viewed?'The barcode brings the right packet to the associate.':scenario==='exception'&&!resolved?'What if a destination label is missing?':shipment.checks.every(Boolean)?'All preparation checks are verified.':'Prepare the shipment, one step at a time.';
 const guideCopy=page==='audit'?'Search the shipment ID and open an event to see the user, status change, and sample output packet.':page==='activity'?'Status counts respond to your preparation and review decisions. Select a shipment to continue its work.':page==='search'?'Try a simulated scan of the Purist faucet shipment bound for Dubai.':shipment.status==='Completed'?'Completion creates a record of who prepared the shipment and what was checked.':shipment.exception?(supervisor?'Enter a resolution above and approve it, or reject the shipment.':'Switch to the supervisor role to review the missing-label exception.'):!viewed?'Open a generated document to see the product, destination, and language pack.':scenario==='exception'&&!resolved?'Record the missing label as an exception. Completion will be blocked until a supervisor resolves it.':shipment.checks.every(Boolean)?'Complete the shipment to create its audit record.':'Verify the three printed documents, review the manifest, then confirm packing. Each step unlocks the next.';
 return <div className="kohlerSurface kd" aria-label="Ship Anywhere interactive sample demo">
  <div className="kd-guide-controls"><span>Try a shipment</span><div role="group" aria-label="Demo scenario"><button type="button" aria-pressed={scenario==='normal'&&guided} onClick={()=>startScenario('normal')}>Normal shipment</button><button type="button" aria-pressed={scenario==='exception'&&guided} onClick={()=>startScenario('exception')}>Missing label</button></div><button type="button" className="kd-guide-toggle" onClick={()=>setGuided(!guided)}>{guided?'Explore freely':'Show walkthrough'}</button></div>
  {guided&&<section className="kd-guide" aria-label="Shipment walkthrough"><ol aria-label="Walkthrough progress">{['Scan','Review','Prepare','Complete','Audit'].map((label,i)=><li key={label} className={i===guideStep?'active':i<guideStep?'done':''}><b>{i<guideStep?'✓':i+1}</b>{label}</li>)}</ol><div className="kd-guide-prompt" aria-live="polite"><div><strong>{guideTitle}</strong><p>{guideCopy}</p></div>{page==='audit'||page==='activity'?<button type="button" className="kd-primary" onClick={()=>startScenario(scenario)}>Replay shipment ↻</button>:page==='search'?<button type="button" className="kd-primary" disabled={scanning} onClick={scanSample}>{scanning?'Scanning…':'Scan sample barcode →'}</button>:shipment.status==='Completed'?<button type="button" className="kd-primary" onClick={()=>{setRole('Supervisor');navigate('audit');setQuery(shipment.id)}}>View shipment audit →</button>:shipment.exception&&!supervisor?<button type="button" className="kd-primary" onClick={()=>setRole('Supervisor')}>Switch to supervisor →</button>:!shipment.exception&&!viewed?<button type="button" className="kd-primary" onClick={()=>preview(0)}>Open sample guide →</button>:!shipment.exception&&scenario==='exception'&&!resolved?<button type="button" className="kd-primary" onClick={()=>{setReason('The destination certification label is missing from the shipment packet.');setDialog({type:'exception'})}}>Record missing label →</button>:shipment.checks.every(Boolean)&&!shipment.exception&&shipment.status!=='Rejected'?<button type="button" className="kd-primary" onClick={complete}>Complete shipment →</button>:null}</div></section>}
  <div className="kd-app-frame">
  <div inert={!!dialog}>
  <header className="kd-header"><strong className="kd-brand">KOHLER</strong><span>Ship Anywhere <small>Sample data</small></span><label className="kd-role"><span className="kd-avatar">{supervisor?'TZ':'JL'}</span><select aria-label="Demo role" value={role} onChange={e=>{setRole(e.target.value);setReason('');if(e.target.value==='Associate'&&['activity','audit'].includes(page))navigate('search')}}><option>Supervisor</option><option>Associate</option></select></label></header>
  <div className="kd-layout"><nav className="kd-nav" aria-label="Shipment workflow">{navigation.filter(([key])=>supervisor||!['activity','audit'].includes(key)).map(([key,label,icon])=><button type="button" key={key} aria-current={page===key?'page':undefined} onClick={()=>navigate(key)}><Icon name={icon}/><span>{label}</span></button>)}<div className="kd-nav-bottom"><span>Interactive prototype</span><button type="button" onClick={reset}>Reset demo</button></div></nav>
   <div className="kd-main">
    {notice&&<div className="kd-notice" role="status">{notice}<button type="button" aria-label="Dismiss notification" onClick={()=>setNotice('')}>×</button></div>}
    {page==='search'&&<><h2>Warehouse Associate Workflow</h2><form className="kd-scan" onSubmit={e=>{e.preventDefault();lookup(scan)}}><Icon name="barcode"/><input aria-label="Scan barcode or enter shipment ID" placeholder="Scan barcode or enter shipment ID" value={scan} onChange={e=>setScan(e.target.value)} disabled={scanning}/><button type="submit" aria-label="Look up shipment" disabled={scanning}><Icon name="search"/></button></form><div className={`kd-scan-demo ${scanning?'is-scanning':''}`}><div className="kd-barcode-label" role="img" aria-label="Sample shipment barcode SHP-10493"><span>SHIP ANYWHERE · DUBAI, UAE</span><svg viewBox="0 0 220 45" aria-hidden="true">{Array.from({length:55},(_,i)=><rect key={i} x={i*4} y="0" width={[1,2,3,1,2,1,3][i%7]} height="45"/>)}</svg><b>SHP-10493</b><i className="kd-scan-line"/></div><div><strong>One scan. The right shipment.</strong><p>Simulate scanning this label to load the product and destination packet.</p><button type="button" disabled={scanning} onClick={scanSample}>{scanning?'Reading barcode…':'Scan this label →'}</button></div></div>{filters()}<div className="kd-card kd-table-card"><div className="kd-table-scroll"><table><thead><tr><th>{sortHeading('Shipment ID','id')}</th><th>Package / Description</th><th>{sortHeading('Destination','destination')}</th><th>{sortHeading('Items','items')}</th><th>{sortHeading('Backlog Age','age')}</th><th>Priority</th><th>{sortHeading('Status','status')}</th></tr></thead><tbody>{visibleShipments.map(s=><tr key={s.id}><td><button className="kd-row-link" type="button" onClick={()=>openShipment(s.id)}>{s.id}</button></td><td><b>{s.name} · {s.sku}</b><small>{s.description}</small></td><td>{s.destination}<small>{s.dock}</small></td><td>{s.items}</td><td>{s.age} {s.age===1?'day':'days'}</td><td><Pill value={s.priority}/></td><td><Pill value={s.status}/></td></tr>)}</tbody></table>{!total&&<div className="kd-empty">No shipments match these filters. Clear the filters to see the worklog.</div>}</div>{pager()}</div></>}
    {page==='work'&&<><div className="kd-work-heading"><div><button className="kd-back" type="button" onClick={()=>navigate('search')}>‹ Shipment Search</button><h2>{shipment.name}</h2><span>SKU: {shipment.sku} <span className="kd-muted">· {shipment.id}</span></span></div><Pill value={shipment.status}/></div><div className="kd-details-grid"><section className="kd-card"><h3>Product Details</h3><p><Icon name="pin"/><span>Destination: <b>{shipment.destination}</b></span></p><p><Icon name="activity"/><span>Order Source: <b>SAP ERP</b></span></p><p><Icon name="globe"/><span>Language Pack: <b>{shipment.language}</b></span></p></section><section className="kd-card"><h3>Generated Documents</h3>{documentNames.map((name,i)=><button className="kd-document" type="button" key={name} onClick={()=>preview(i)}><b>{name}</b><small>{['Guide','Label','Certificate'][i]}_{shipment.language.split(',')[0]}.sample · Preview ↗</small></button>)}</section></div>
     {shipment.exception&&<section className="kd-exception"><b>{shipment.review==='Rejected'?'Shipment rejected':'Needs supervisor review'}</b><p>{shipment.exception}</p>{supervisor&&shipment.review!=='Rejected'?<><label>Resolution or rejection reason<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain how the issue was resolved or why it cannot proceed…"/></label><div className="kd-actions"><button type="button" className="kd-primary" disabled={!reason.trim()} onClick={()=>review(true)}>Approve resolution</button><button type="button" disabled={!reason.trim()} onClick={()=>review(false)}>Reject shipment</button></div></>:<p className="kd-muted">{supervisor?'Reopen the shipment below to begin corrections.':'A supervisor must review this issue before you can continue.'}</p>}</section>}
     <section className="kd-card kd-instructions"><h3>Work Instructions</h3><div className="kd-progress"><span>{shipment.checks.filter(Boolean).length} of 5 checks completed</span><progress max="5" value={shipment.checks.filter(Boolean).length}/></div>{[0,1,2].map((step)=>{const available=step===0||(step===1?shipment.checks.slice(0,3).every(Boolean):shipment.checks.slice(0,4).every(Boolean));const done=step===0?shipment.checks.slice(0,3).every(Boolean):shipment.checks[step+2];return <div className={`kd-step ${!available?'kd-upcoming':''}`} key={step}><span className="kd-step-number">{done?'✓':step+1}</span><div className="kd-step-body"><div className="kd-step-meta"><b>Step {step+1}</b><span>{done?'Completed':available?'In progress':'Upcoming'}</span></div><strong>{['Print Shipment Documents','Review Shipment Manifest','Pack All Items and Prepare for Shipping'][step]}</strong><p>{['Print all required documents for customs clearance and local compliance.','Confirm the product, quantity, and destination match the shipment record.','Attach the destination documents and verify every item is packed.'][step]}</p><div className="kd-task-list">{(step===0?[0,1,2]:[step+2]).map(i=><label key={i}><input type="checkbox" checked={shipment.checks[i]} disabled={!available||!!shipment.exception||['Completed','Rejected'].includes(shipment.status)} onChange={()=>toggleTask(i)}/><span>{tasks[i]}<small>{i<3?`${shipment.language} · ${shipment.destination}`:`${shipment.items} items · ${shipment.sku} · ${shipment.dock}`}</small></span></label>)}</div></div></div>})}<div className="kd-work-footer"><button type="button" disabled={['Completed','Rejected'].includes(shipment.status)||!!shipment.exception} onClick={()=>{setReason('');setDialog({type:'exception'})}}>Record exception</button>{shipment.status==='Rejected'?<button type="button" className="kd-primary" onClick={()=>{updateShipment({status:'Needs Review',review:'Needs Review',checks:Array(5).fill(false)},'Reopened for correction','Shipment reopened; supervisor must resolve the outstanding issue.');setNotice('Reopened for correction. Resolve the exception above.')}}>Reopen for correction</button>:<button type="button" className="kd-primary" disabled={shipment.status==='Completed'||!shipment.checks.every(Boolean)||!!shipment.exception||['Needs Review','Halted'].includes(shipment.status)} onClick={complete}>{shipment.status==='Completed'?'Shipment completed':'Complete shipment'}</button>}</div></section></>}
    {page==='activity'&&<><h2>Activity Overview</h2><div className="kd-metrics">{[[['document',98,'Total Shipments'],['check',completed,'Completed'],['activity',progress,'In Progress']],[['box',pending,'Pending'],['pin',halted,'Halted'],['audit',inReview,'In Review']],[['clock','92%','On-time Rate'],['activity','2.4 hrs','Avg. Processing Time'],['box',pending+halted+inReview,'Current Backlog']]].map((group,i)=><section className="kd-card" key={i}>{group.map(([icon,value,label])=><div className="kd-metric" key={label}><Icon name={String(icon)}/><div><b>{value}</b><small>{label}</small></div></div>)}</section>)}</div><section className="kd-card kd-table-card"><h3>Recent Shipment Activity Log</h3>{filters()}<div className="kd-table-scroll"><table><thead><tr><th>Shipment ID</th><th>Destination</th><th>Status</th><th>Priority</th><th>Assigned Team</th><th>Updated Time</th></tr></thead><tbody>{activityShipments.slice(0,6).map(s=><tr key={s.id}><td><button type="button" className="kd-row-link" onClick={()=>openShipment(s.id)}>{s.id}</button></td><td>{s.destination}</td><td><Pill value={s.status}/></td><td><Pill value={s.priority}/></td><td>{s.team}</td><td>{formatTime(events.find(e=>e.shipment===s.id)?.timestamp||`${s.date}T08:00:00`)}</td></tr>)}</tbody></table>{!filteredShipments.length&&<div className="kd-empty">No activity matches these filters.</div>}</div></section><div className="kd-charts"><section className="kd-card"><h3>Shipment Status Distribution</h3><div className="kd-distribution"><div className="kd-donut" style={{background:`conic-gradient(${donut})`}} role="img" aria-label={distribution.map(([label,n])=>`${label}: ${n}`).join(', ')}><span><b>98</b><small>Total</small></span></div><ul>{distribution.map(([label,n,color])=><li key={label}><i style={{background:color}}/>{label}<b>{n} ({Math.round(n/98*100)}%)</b></li>)}</ul></div></section><section className="kd-card"><h3>Shipments Processed Over Time</h3><div className="kd-chart-key"><span>■ Completed</span><span>■ Total</span></div><div className="kd-bars" role="img" aria-label="Sample April 1 to April 30 processing trend. Dark bars show completed shipments; light bars show total shipments.">{Array.from({length:30},(_,i)=>{const n=12+(i*7)%24;return <span key={i} style={{height:`${n*2.2}%`}}><i style={{height:`${30+(i*3)%45}%`}}/></span>})}</div><div className="kd-chart-dates"><span>Apr 1</span><span>Apr 7</span><span>Apr 14</span><span>Apr 21</span><span>Apr 30</span></div></section></div><p className="kd-dashboard-note">Sample warehouse snapshot. Counts update as you work; performance and trend figures are illustrative.</p></>}
    {page==='audit'&&<><h2>Audit History View</h2>{filters(true)}<div className="kd-card kd-table-card"><div className="kd-table-scroll"><table className="kd-audit-table"><thead><tr><th>{sortHeading('Timestamp','timestamp')}</th><th>{sortHeading('Shipment ID','shipment')}</th><th>{sortHeading('Activity','activity')}</th><th>{sortHeading('User','user')}</th><th>Previous Status</th><th>{sortHeading('New Status','next')}</th><th>Location</th><th>Details</th></tr></thead><tbody>{visibleEvents.map(e=><tr key={e.id}><td>{formatTime(e.timestamp)}</td><td><button type="button" className="kd-row-link" onClick={()=>openShipment(e.shipment)}>{e.shipment}</button></td><td>{e.activity}</td><td>{e.user}</td><td>{e.previous==='—'?'—':<Pill value={e.previous}/>}</td><td><Pill value={e.next}/></td><td>{e.location}</td><td><button type="button" className="kd-event-link" onClick={()=>setDialog({type:'event',event:e})}>{e.details} <span>↗</span></button></td></tr>)}</tbody></table>{!total&&<div className="kd-empty">No audit events match these filters.</div>}</div>{pager(true)}</div></>}
   </div>
  </div>
  <footer className="kd-demo-footer">Portfolio demo · Predefined shipments and sample documents · Changes last until reset or refresh.</footer>
  </div>
  {dialog&&<div className="kd-modal-layer" onClick={e=>{if(e.target===e.currentTarget)setDialog(null)}}><div ref={dialogRef} className="kd-dialog" role="dialog" aria-modal="true" aria-label={dialog.type==='exception'?'Record shipment exception':dialog.type==='event'?'Shipment audit details':'Sample shipment document'} onKeyDown={dialogKeys}><div className="kd-dialog-content"><button type="button" className="kd-dialog-close" aria-label="Close dialog" onClick={()=>setDialog(null)}>×</button>
   {dialog?.type==='document'&&<><span className="kd-eyebrow">Sample document · A4 packet</span><h2>{documentNames[dialog.index!]}</h2><div className="kd-sample-paper"><strong>KOHLER</strong><h3>{dialogShipment.name}</h3><dl><dt>Shipment</dt><dd>{dialogShipment.id}</dd><dt>Product SKU</dt><dd>{dialogShipment.sku}</dd><dt>Destination</dt><dd>{dialogShipment.destination}</dd><dt>Language pack</dt><dd>{dialogShipment.language}</dd><dt>Document status</dt><dd>{dialogShipment.review}</dd></dl><p>{['Include the destination-language installation guide in the shipment packet. Verify the product SKU matches the guide before packing.','Verify that the destination warranty label is present and matches the product before applying it.','Confirm the required destination certification label is available and reviewed before packing.'][dialog.index!]}</p><aside>Sample content for this portfolio demo. No approved translation, warranty terms, or certification is supplied.</aside></div><button type="button" className="kd-primary" onClick={()=>downloadSample(dialog.index!,dialogShipment)}>Download sample (.txt)</button></>}
   {dialog?.type==='exception'&&<form onSubmit={e=>{e.preventDefault();if(!reason.trim())return;updateShipment({status:'Needs Review',exception:reason.trim(),review:'Needs Review'},'Exception recorded',reason.trim());setDialog(null);setReason('');setNotice('Exception recorded. Completion is blocked until a supervisor resolves it.')}}><span className="kd-eyebrow">{shipment.id}</span><h2>Record an exception</h2><p>Describe the missing document, label, or preparation issue. This will stop completion and send the shipment for review.</p><label>Exception details<textarea required autoFocus value={reason} onChange={e=>setReason(e.target.value)} placeholder="For example: the destination warranty label is missing."/></label><button type="submit" className="kd-primary" disabled={!reason.trim()}>Submit for review</button></form>}
   {dialog?.type==='event'&&<><span className="kd-eyebrow">Shipment audit record</span><h2>{dialog.event!.activity}</h2><dl><dt>Shipment</dt><dd>{dialogShipment.id}</dd><dt>Product / SKU</dt><dd>{dialogShipment.name} / {dialogShipment.sku}</dd><dt>Destination</dt><dd>{dialogShipment.destination}</dd><dt>Processed by</dt><dd>{dialog.event!.user}</dd><dt>Timestamp</dt><dd>{formatTime(dialog.event!.timestamp)}</dd><dt>Status transition</dt><dd>{dialog.event!.previous} → {dialog.event!.next}</dd><dt>Details</dt><dd>{dialog.event!.details}</dd></dl><h3>Sample output packet</h3>{documentNames.map((name,i)=><button type="button" className="kd-document" key={name} onClick={()=>preview(i,dialogShipment)}>{name} ↗</button>)}</>}
  </div></div></div>}
  </div>
 </div>;
}
